strerror: move to cstring.
It turns out that perror functions are in cstdio, and strerror in cstring.

	* include/libport/cstdio, lib/libport/cstdio.cc
	(getWinErrorMessage, strerror): Move to...
	* include/libport/cstring, lib/libport/cstring.cc: here.
	* lib/libport/local.mk: Adjust.